// Generated by scripts/build-ipfs-static-config.mjs from .env — do not edit by hand.
window.__IPFS_GATEWAY = {
  domain: "ipfs.publishednft.io",
  token: "u6tBABnQ0w4Agk-YH-iDqtfWLBwtDxJdknjvEN_wijOFsStZ0d8HavSiOLjQ3ojy",
}
